ckpt_dir: null
ckpt_root: null
clean_save: false
dataset:
  dataloader_name: BaseDataLoader
  dataset_root: null
  dim_edge: null
  dim_node: null
  generate: false
  num_classes: null
  num_envs: null
exp_round: null
gpu_idx: 0
log_file: default
model:
  dim_ffn: 300
  dim_hidden: 300
  dropout_rate: 0.5
num_workers: 0
ood:
  extra_param: null
pipeline: Pipeline
pytest: false
random_seed: 114
save_tag: null
task: train
train:
  alpha: 0.2
  ctn_epoch: 0
  epoch: 0
  save_gap: 10
  stage_stones: []
  tr_ctn: false
  weight_decay: 0.0
